name: tf_gpu
channels:
  - defaults
  - conda-forge
dependencies:
  - tensorflow-gpu=1.12.0
  - numpy=1.15.4
  - tweepy=1.5.0
  - pandas=0.23.4
  - scikit-learn=0.20.0
  - nltk=3.3.0
  - matplotlib=3.0.2
  - regex=2018.11.22
