name: tf_gpu
channels:
  - defaults
  - conda-forge
dependencies:
  - asn1crypto=0.24.0
  - blinker=1.4
  - ca-certificates=2018.10.15
  - certifi=2018.10.15
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.3.1
  - cryptography-vectors=2.3.1
  - hdf5=1.10.2
  - idna=2.7
  - libprotobuf=3.5.2
  - oauthlib=2.1.0
  - openssl=1.0.2o
  - protobuf=3.5.2
  - pycparser=2.19
  - pyjwt=1.6.4
  - pyopenssl=18.0.0
  - pysocks=1.6.8
  - requests=2.20.1
  - requests-oauthlib=1.0.0
  - tweepy=3.6.0
  - urllib3=1.23
  - win_inet_pton=1.0.1
  - zlib=1.2.11
  - _tflow_190_select=0.0.1
  - _tflow_select=2.1.0
  - absl-py=0.6.1
  - astor=0.7.1
  - blas=1.0
  - cudatoolkit=9.0
  - cudnn=7.1.4
  - gast=0.2.0
  - grpcio=1.12.1
  - h5py=2.8.0
  - icc_rt=2017.0.4
  - intel-openmp=2019.1
  - keras-applications=1.0.6
  - keras-preprocessing=1.0.5
  - markdown=3.0.1
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - numpy=1.15.4
  - numpy-base=1.15.4
  - pandas=0.23.4
  - pip=18.1
  - python=3.6.6
  - python-dateutil=2.7.5
  - pytz=2018.7
  - scipy=1.1.0
  - setuptools=40.6.2
  - six=1.11.0
  - tensorboard=1.9.0
  - tensorflow=1.9.0
  - tensorflow-base=1.9.0
  - tensorflow-gpu=1.9.0
  - termcolor=1.1.0
  - vc=14
  - vs2015_runtime=14.15.26706
  - werkzeug=0.14.1
  - wheel=0.32.3
  - wincertstore=0.2

